field: 31889cbb-c3af-425c-9032-402eb093b350
fieldLayouts:
  ac4dab59-5dea-44ef-961b-ca06926c9f52:
    tabs:
      -
        elements:
          -
            fieldUid: eaf3ed3d-f560-46cc-9abb-8938fc9d23dc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 77875512-9b22-4334-9499-800bce93ef61
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: df752805-c64f-4306-995b-cfd317e93fe0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  77875512-9b22-4334-9499-800bce93ef61:
    contentColumnType: string
    fieldGroup: null
    handle: contentPost
    instructions: ''
    name: 'Content post'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources:
        - 'section:00db5c32-bd52-481b-aa3c-f479d9a0dca5'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  df752805-c64f-4306-995b-cfd317e93fe0:
    contentColumnType: text
    fieldGroup: null
    handle: tailwindClass
    instructions: ''
    name: 'Tailwind class'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  eaf3ed3d-f560-46cc-9abb-8938fc9d23dc:
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: ''
    name: Header
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: featuredPost
name: 'Featured post'
sortOrder: 2
