field: 31889cbb-c3af-425c-9032-402eb093b350
fieldLayouts:
  16f9c2dd-d556-4b35-a55f-9108736b00b9:
    tabs:
      -
        elements:
          -
            fieldUid: ad11becb-3841-4d44-81bf-95585fefd0ab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 518a032e-69a5-4e18-80cc-97642efdd614
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b6ac1a0b-a0fa-449b-84d0-84c723e83666
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  518a032e-69a5-4e18-80cc-97642efdd614:
    contentColumnType: integer(10)
    fieldGroup: null
    handle: postLimit
    instructions: ''
    name: 'Post limit'
    searchable: false
    settings:
      decimals: 0
      defaultValue: '4'
      max: null
      min: '0'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  ad11becb-3841-4d44-81bf-95585fefd0ab:
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: ''
    name: Header
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b6ac1a0b-a0fa-449b-84d0-84c723e83666:
    contentColumnType: text
    fieldGroup: null
    handle: tailwindClass
    instructions: ''
    name: 'Tailwind class'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recentPost
name: 'Recent post'
sortOrder: 5
