fieldLayouts:
  48ae54ae-e55f-48b0-80ac-1f16ddb44c09:
    tabs:
      -
        elements:
          -
            heading: 'Your name/company name'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 05483dc7-c41a-4db3-af9d-a6bec723a610
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: 'Paragraph containing you/company information'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: a561ed63-1cbe-464d-b414-6a5e64025e36
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: __blank__
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: About
        sortOrder: 1
handle: about
hasTitleField: false
name: About
section: 54986972-49ef-4942-ba88-cbda004efbfd
sortOrder: 1
titleFormat: About
titleTranslationKeyFormat: null
titleTranslationMethod: site
