contentColumnType: string
fieldGroup: f9485060-f9ef-404b-8ba4-315216539b24
handle: multiParagraph
instructions: ''
name: 'Multi paragraph'
searchable: false
settings:
  contentTable: '{{%matrixcontent_multiparagraph}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
