enableVersioning: false
handle: about
name: About
propagationMethod: all
siteSettings:
  36134da6-fef0-4b3a-997c-5f5f9a6897f6:
    enabledByDefault: true
    hasUrls: true
    template: about
    uriFormat: about
type: single
